### ISSUE TITLE
install from MELPA without the SQLite shell

### ISSUE THREAD

**Issue by tzz** [skeeto/emacsql#15]
I use PG exclusively and would prefer to avoid installing unneedded external binaries when I install Emacs packages.

I'm not sure if this requires splitting the MELPA package or something else, but there doesn't currently seem to be a way to install without the SQLite shell.

Thanks for looking...

**Comment by skeeto** [comment]
I believe you can disable it with these two variables:

* emacsql-sqlite-automatic-fetch
* emacsql-sqlite-automatic-build

Set the first to 'no and the second to nil. Short of a bug, it will only
try to build if a SQLite connection is attempted.

**Comment by tzz** [comment]
I don't think setting variables is easy to do from a package install.  Joe Random User would not know to set those variables beforehand.

I understand the convenience of the automatic version but I also don't know of other Emacs packages that do it this way.  Would you consider splitting the package into `emacsql-base` and `emacsql` for instance?  The second one would look right to users so you wouldn't end up with many installing the first one.

**Comment by skeeto** [comment]
Oh, I understand now. I thought this was just for your own personal use.
You're building a package depending on EmacSQL, but only for PostgreSQL,
and don't want to bother your users with an unrelated SQLite binary.

I think you've got the right idea: split off a separate emacsql-sqlite
package. That shouldn't be too difficult. It will temporarily break
EmacSQL for others who use the SQLite part, until they also add
emacsql-sqlite to their dependencies.

**Comment by tarsius** [comment]
While you are at it, could you please also create a separate package for `emacsql-pg.el` (possibly named `emacsql-psql` and also including `emacssql-psql.el`), that would avoid forcing the dependency on `pg` on users who are only interested in SQLite and/or MySQL (which you might as well also split into a separate package).

**Comment by tzz** [comment]
Unfortunately I can't manage the MELPA recipes for your package, you have to do it.  I think you and @tarsius are right, basically split the UI implementation from the various backends.

You could say it's emacsql2 or mark it as version 2 to indicate that a direct upgrade probably won't work, for users who expect SQLite from the base package.  But honestly I think there's always going to be complaints, it's just how it goes :)  From my side, I like the package and appreciate your work on it.

**Comment by skeeto** [comment]
Alright, this weekend I'll split off emacsql-sqlite, emacsql-psql, and
(for consistency) emacsql-mysql as new MELPA packages. In addition to
the MELPA recipe changes, they'll also need their own package headers.
I'll tag a new release for it, too.

**Comment by tzz** [comment]
Thank you!!!

**Comment by tarsius** [comment]
Thanks a lot.
