### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by tarsius** [skeeto/emacsql#20]
I plan to re-announce the Emacsmirror on Monday. I'll then also release `epkg.el` a tool for browsing metadata extracted from the mirrored packages. That uses `emacsql-sqlite` and depends on the recent changes.

Could you please create a new minor release so that `epkg.el` can be installed from Melpa Stable as soon as I announce it. Thanks a lot!

**Comment by skeeto** [comment]
I bumped the core to 2.0.1 but re-reading this I see you specifically need emacsql-sqlite bumped up. I'm unsure how this works with MELPA stable. It's split into multiple packages and MELPA can't distinguish how Git's tags apply between them, so do I need to keep all the packages lock-step on the same version number?

**Comment by tarsius** [comment]
Uh, I forgot about that. I am not 100% what will happen, but I think all packages will be bumped, not just those that changed since the last commit. Let's wait until the rebuild is complete, then we'll see. If only `emacsql` is bumped, then that's not much of an issue for me, I would just depend on `emacsql-2.0.1` in addition to `emacsql-sqlite-2.0.0`.

**Comment by tarsius** [comment]
They all went up.

**Comment by tarsius** [comment]
Could you please create another release?

Last time you did so on a dedicated branch, i.e. `2.0.3` is not reachable from `master`. I guess that was an accident.

**Comment by tarsius** [comment]
Thanks a lot!
