### ISSUE TITLE
quoting results?

### ISSUE THREAD

**Issue by jkitchin** [skeeto/emacsql#23]
I have a sqlite database that has entries like "Message from Unknown sender" in a column. But if I do something like 

(emacsql db [:select [messageID arrivalTime subject callerIdCallerName]
					  :from 'Voicemails])

I get results like:
(0:ce02a3fb-6ff0-4d67-b6dd-1dbcd2c8bf1a 1475008083000 Message from Unknown sender (Unknown caller ID))

That list has more than 4 elements in it (it has 7). But this isn't useful since the strings are not quoted. Is there a way to get the results from columns quoted?

**Comment by skeeto** [comment]
EmacSQL isn't intended to be a generic SQL database interface but rather
a system that allows Emacs to use a SQL databse to back its own data.
All database values must be stored in s-expression form, so the database
is essentially limited to use by EmacSQL itself.

**Comment by jkitchin** [comment]
Ok, thanks for the clarification!
