### ISSUE TITLE
full text search syntax

### ISSUE THREAD

**Issue by jkitchin** [skeeto/emacsql#26]
Is it possible to get this full text search syntax?

SELECT headline_id, content FROM headline_content WHERE headline_content 
    MATCH '"alloy" NEAR "neural"';

I got close with 

(emacsql org-db [:select [headline-id content] :from
		 headline-content 
		 :where headline-content :match "alloy" :NEAR "neural"])

but it generates

SELECT headline_id, content FROM headline_content WHERE headline_content 
    MATCH '"alloy"' NEAR '"neural"';

and the single quotes are not right.

**Comment by skeeto** [comment]
The problem is that the s-expression form can't express raw string
values. All lisp values are printed before going out to SQL. You can get
around this by passing a query string to the emacsql function instead of
a query vector:

    (emacsql db "SELECT foo FROM bar")

But it has two issues: 1) You miss out on prepared statements and fall
back to constructing your own strings, and 2) You must ensure that the
results are all readable lisp values. I've never used FTS in SQLite so I
don't know the caveats, but be aware that a partial result from a string
value in the database won't work right since it can't be (read) into
Emacs. You'll also be matching against the printed versions of any
values.

**Comment by jkitchin** [comment]
Thanks for the help (again ;). I wrote this http://kitchingroup.cheme.cmu.edu/blog/2017/01/03/Find-stuff-in-org-mode-anywhere/ on what I have been using emacsql for so far. I left out the FTS part because the sqlite database got large and a little slow. I will get back to it one day.

**Comment by skeeto** [comment]
Those are some nice examples of EmacSQL in action. Your needs have me
thinking about what it would take to add support for "raw" strings which
do not get printed but are used directly as values, so that you could
properly specify LIKE and FTS operands.

**Comment by jkitchin** [comment]
Thanks. I think it would be great to use those.

**Comment by jkitchin** [comment]
Just circling around to show an example of how this works. TL;DR: it works great!


```
#+BEGIN_SRC emacs-lisp
(setq db (emacsql-sqlite "ft.sqlite"))


(emacsql db [:create-virtual-table :if :not :exists posts
				   :using :fts5
				   ([title body])])


(cl-loop for (title body) in '(("Learn SQlite FTS5" "This tutorial teaches you how to perform full-text search in SQLite using FTS5")
			       ("Advanced SQlite Full-text Search" "Show you some advanced techniques in SQLite full-text searching")
			       ("SQLite Tutorial" "Help you learn SQLite quickly and effectively"))
	 do
	 (emacsql db [:insert :into posts :values [$s1 $s2]] title body))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(emacsql db [:select [*] :from posts])
#+END_SRC

#+RESULTS:
| Learn SQlite FTS5                | This tutorial teaches you how to perform full-text search in SQLite using FTS5 |
| Advanced SQlite Full-text Search | Show you some advanced techniques in SQLite full-text searching                |
| SQLite Tutorial                  | Help you learn SQLite quickly and effectively                                  |

#+BEGIN_SRC emacs-lisp
(emacsql db [:select [*] :from posts :where posts :match '"fts5"])
#+END_SRC

#+RESULTS:
| Learn SQlite FTS5 | This tutorial teaches you how to perform full-text search in SQLite using FTS5 |

#+BEGIN_SRC emacs-lisp
(emacsql db [:select [*] :from posts :where (= posts "search*")])
#+END_SRC

#+RESULTS:
| Learn SQlite FTS5                | This tutorial teaches you how to perform full-text search in SQLite using FTS5 |
| Advanced SQlite Full-text Search | Show you some advanced techniques in SQLite full-text searching                |
```
