### ISSUE TITLE
another syntax question

### ISSUE THREAD

**Issue by jkitchin** [skeeto/emacsql#27]
I am trying to get some emacsql code that generates:

SELECT headlines.title AS a1, tags.tag AS a2 FROM

:select [headlines:title] :as a1

generates the first part, but I don't know how to get the second part. None of the efforts at nesting tags.tag have worked,

eg :select [headlines:title tags:tag] :as a2

leads to SELECT headlines.title, tags.tag AS a2 

Any hints?

**Comment by skeeto** [comment]
In this situation, the "AS" is just another operator in the output
column expression.

    [:select [(as headlines:title a1) (as tags:tag a2)]
     :from foo :as f]

I included a second example: when using "AS" for a table alias, use
":as" since it's not really being used an expression operator in that
situation. I hope that makes sense.

**Comment by jkitchin** [comment]
That does make sense. thanks!
