### ISSUE TITLE
Not able to download sqlite binary for Windows

### ISSUE THREAD

**Issue by romanab** [skeeto/emacsql#29]
I installed the emacsql package and started going through the example. Upon doing 

ELISP> (defvar db (emacsql-sqlite "~/company.db"))
*** Eval error ***  No EmacSQL SQLite binary available, aborting

I agree to download the binary but it doesn't get past displaying
Contacting host: nullprogram.s3.amazonaws.com:80

Is the 2.0.2 binary available?

**Comment by skeeto** [comment]
I forgot to add "2.0.2" binaries to S3 (and 2.0.0, and 2.0.1). They're
exactly the same as 1.0.2, but EmacSQL 2.0.2 wants to find them under
its own version number. That should be fixed now. Try again and tell me
if it works or not.

Thanks for the heads up!

**Comment by romanab** [comment]
Actually, I used your post to download the Msys toolchain and compiled it locally.  I left the issue opened as others might encounter the same problem. Thanks.
