### ISSUE TITLE
No way to select un(read)able strings in the db

### ISSUE THREAD

**Issue by jordonbiondo** [skeeto/emacsql#4]
From what I can tell there is no way for me to select strings from my db that can't be read by (read).

I am using mysql and am selecting values that contain the # character, and this errors on read. 

My initial solution was to try to select the values as readable strings by concatenating string delimiters around the values but I can't get those queries to build correctly.

I could get around the problem if I could build something like:

    SELECT Concat('"', textvalue, '"') FROM mytable;

So that the values are readable, but doing:

   (emacsql db [:select [(funcall Concat "\"" textvalue "\"")] :from mytable])

yields results like:

    "\""value"\""

instead of:
 
    "value"

and when using \" instead of "\"" emacsql tries to use \" as a column name.

I've also tried using the Quote function which only uses single quotes, and I get errors when using REPLACE, it seems my REPLACE funcalls maybe aren't built right.

Is there a solution I'm missing or is this not supported?

Perhaps I can go down lower and manually replace #s with \#s when the data comes back but that doesn't feel like the best solution.

Thanks.

**Comment by jordonbiondo** [comment]
> The high level idea is that EmacSQL isn't really intended for interacting with existing databases, but for being a high-quality database for Emacs extensions. Saving printed s-expressions to files only scales so far, which is a limit I've run into with Elfeed.

Thanks, that answers it, closing.

**Comment by Lenin1917** [comment]
This is concat for sqlite
```
(emacsql db "SELECT ('\"' || textvalue ||'\"') FROM mytable")
```
