### ISSUE TITLE
make sqlite fail?

### ISSUE THREAD

**Issue by iT-Boyer** [skeeto/emacsql#57]
macOS 10.15 
xcode 11
```
cd ~/.emacs.d/elpa/develop/emacsql-sqlite-20190727.1710/sqlite
make
```
log: sqlite3.c:20071:24: error: unknown type name ‘time_t’; did you mean ‘size_t’?

**Comment by skeeto** [comment]
This looks like a broken C toolchain on your system. The SQLite source 
includes the standard header time.h which defines time_t. Your C 
compiler must be able to compile this program without that error:

#include <time.h>
#include <stdio.h>
int main(void)
{
    time_t t = time(0);
    printf("%lu\n", (unsigned long)t);
    return 0;
}

Using something like this:

$ cc example.c

If it can't, then it's definitely a problem with your toolchain.

**Comment by huos3203** [comment]
> #include <time.h> #include <stdio.h> int main(void) { time_t t = time(0); printf("%lu\n", (unsigned long)t); return 0; }
it is error when i try run `cc test.c `
```
test.c:11:5: error: unknown type name 'time_t'; did you mean 'size_t'?
```

**Comment by skeeto** [comment]
Yeah, your C toolchain is broken. You'll have to figure out how to fix 
that before using EmacSQL. Maybe try searching for that error message 
along with the version of your operating system, or the name of wherever 
you got your compiler. Or maybe just reinstall the compiler. Ultimately 
that small example C source I gave you must compile and run cleanly. Use 
it to test your C toolchain as you try to fix it.
