### ISSUE TITLE
emacsql-foreign-key test fails with newer sqlite

### ISSUE THREAD

**Issue by spwhitton** [skeeto/emacsql#63]
I'm packaging emacsql for Debian and want to build the emacsql-sqlite binary against the system libsqlite3.  This seems to be working fine except there is one test failure, as shown below.  I think this might be because emacsql needs to be updated in order to be used with newer sqlite?

    Test emacsql-foreign-key backtrace:
      signal(ert-test-failed (((should (equal (emacsql db [:select * :from
      ert-fail(((should (equal (emacsql db [:select * :from likes]) '((1 y
      (if (unwind-protect (setq value-29 (apply fn-27 args-28)) (setq form
      (let (form-description-31) (if (unwind-protect (setq value-29 (apply
      (let ((value-29 'ert-form-evaluation-aborted-30)) (let (form-descrip
      (let* ((fn-27 (function equal)) (args-28 (condition-case err (let ((
      (progn (let ((emacsql--conn db)) (let ((emacsql--connection emacsql-
      (unwind-protect (progn (let ((emacsql--conn db)) (let ((emacsql--con
      (progn (unwind-protect (progn (let ((emacsql--conn db)) (let ((emacs
      (unwind-protect (progn (unwind-protect (progn (let ((emacsql--conn d
      (let ((db (funcall (cdr factory)))) (unwind-protect (progn (unwind-p
      (let ((factory (car --dolist-tail--))) (let ((db (funcall (cdr facto
      (while --dolist-tail-- (let ((factory (car --dolist-tail--))) (let (
      (let ((--dolist-tail-- emacsql-tests-connection-factories)) (while -
      (let ((emacsql-global-timeout emacsql-tests-timeout)) (let ((--dolis
      (closure (t) nil (let ((emacsql-global-timeout emacsql-tests-timeout
      ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
      ert-run-test(#s(ert-test :name emacsql-foreign-key :documentation "T
      ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
      ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
      ert-run-tests-batch(nil)
      ert-run-tests-batch-and-exit()
      eval((ert-run-tests-batch-and-exit))
      command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
      command-line()
      normal-top-level()
    Test emacsql-foreign-key condition:
        (ert-test-failed
         ((should
           (equal
    	(emacsql db
    		 [:select * :from likes])
    	'...))
          :form
          (equal
           ((0 red)
    	(0 yellow)
    	(1 yellow))
           ((1 yellow)))
          :value nil :explanation
          (proper-lists-of-different-length 3 1
    					((0 red)
    					 (0 yellow)
    					 (1 yellow))
    					((1 yellow))
    					first-mismatch-at 0)))
       FAILED  11/23  emacsql-foreign-key

**Comment by skeeto** [comment]
It's because the system SQLite is compiled with different defaults than the embedded one. The build-time options are listed in `sqlite/Makefile`, most importantly `-DSQLITE_DEFAULT_FOREIGN_KEYS=1`. This is part of normalizing the interfaces between the various supported SQLite databases: Foreign keys are always enabled by default in EmacSQL.

Here's a patch that switches to the system SQLite and enables foreign keys by default, allowing the tests to pass. You're probably most interested in the first hunk:

```diff
diff --git a/emacsql-sqlite.el b/emacsql-sqlite.el
index b14d1ac..6937d2f 100644
--- a/emacsql-sqlite.el
+++ b/emacsql-sqlite.el
@@ -100,6 +100,7 @@ used.")
     (emacsql-wait connection)
     (emacsql connection [:pragma (= busy-timeout $s1)]
              (/ (* emacsql-global-timeout 1000) 2))
+    (emacsql connection [:pragma (= foreign_keys 1)])
     (emacsql-register connection)))
 
 (cl-defun emacsql-sqlite (file &key debug)
@@ -163,12 +164,12 @@ If called with non-nil ASYNC the return value is meaningless."
                       if path return it))
          (src (expand-file-name "sqlite" emacsql-sqlite-data-root))
          (files (mapcar (lambda (f) (expand-file-name f src))
-                        '("sqlite3.c" "emacsql.c")))
+                        '("emacsql.c")))
          (cflags (list (format "-I%s" src) (format "-O%d" (or o-level 2))))
          (ldlibs (cl-case system-type
                    (windows-nt (list))
                    (berkeley-unix (list "-lm"))
-                   (otherwise (list "-lm" "-ldl"))))
+                   (otherwise (list "-lm" "-ldl" "-lsqlite3"))))
          (options (emacsql-sqlite-compile-switches))
          (output (list "-o" emacsql-sqlite-executable))
          (arguments (nconc cflags options files ldlibs output)))
```

**Comment by spwhitton** [comment]
Hello Chris,

Thank you for your reply.  In addition to applying the patch I will be
adding a README.Debian explaining the issue.

-- 
Sean Whitton
